### ISSUE TITLE
galera PVC size with lvm-operator issue

### ISSUE THREAD

**Issue by clopnis** [openstack-k8s-operators/install_yamls#747]
I case of usage of lvm-operator as storage classe it create an issue with PVC of galera

From statefulset.apps/openstack-galera
```
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 500M
```

from PVC of galera
```
  Warning  ProvisioningFailed    95s (x14 over 20m)  topolvm.io_lvms-operator-59ccff4765-lw7n2_26e92801-35c3-4658-ab70-0c03e827f50a  failed to provision volume with StorageClass "lvms-vg1": rpc error: code = Internal desc = exit status 3: Size is not a multiple of 512. Try using 499999744 or 500000256.
  Invalid argument for --virtualsize: 500000000b
```
